spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
server:
  port: 8081
  servlet:
    context-path: /dev

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.204.164/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  profiles: test
server:
  port: 8082
  servlet:
    context-path: /test

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.204.164/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

